/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : RxBuf.h
**     Project     : MCUX_PE_KL25Z_FRTOS_SerialEcho
**     Processor   : MKL25Z128VLK4
**     Component   : RingBuffer
**     Version     : Component 01.053, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-10-17, 19:46, # CodeGen: 0
**     Abstract    :
**         This component implements a ring buffer for different integer data type.
**     Settings    :
**          Component name                                 : RxBuf
**          Buffer Size                                    : 64
**     Contents    :
**         Clear           - void RxBuf_Clear(void);
**         Put             - uint8_t RxBuf_Put(RxBuf_ElementType elem);
**         Get             - uint8_t RxBuf_Get(RxBuf_ElementType *elemP);
**         Peek            - uint8_t RxBuf_Peek(RxBuf_BufSizeType index, RxBuf_ElementType *elemP);
**         Update          - uint8_t RxBuf_Update(RxBuf_BufSizeType index, RxBuf_ElementType *elemP);
**         Putn            - uint8_t RxBuf_Putn(RxBuf_ElementType *elem, RxBuf_BufSizeType nof);
**         Getn            - uint8_t RxBuf_Getn(RxBuf_ElementType *buf, RxBuf_BufSizeType nof);
**         Compare         - uint8_t RxBuf_Compare(RxBuf_BufSizeType index, RxBuf_ElementType *elemP,...
**         Delete          - uint8_t RxBuf_Delete(void);
**         NofElements     - RxBuf_BufSizeType RxBuf_NofElements(void);
**         NofFreeElements - RxBuf_BufSizeType RxBuf_NofFreeElements(void);
**         Deinit          - void RxBuf_Deinit(void);
**         Init            - void RxBuf_Init(void);
**
**Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**All Rights Reserved.
**
**Redistribution and use in source and binary forms, with or without modification,
**are permitted provided that the following conditions are met:
**
**o Redistributions of source code must retain the above copyright notice, this list
**  of conditions and the following disclaimer.
**
**o Redistributions in binary form must reproduce the above copyright notice, this
**  list of conditions and the following disclaimer in the documentation and/or
**  other materials provided with the distribution.
**
**o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**  contributors may be used to endorse or promote products derived from this
**  software without specific prior written permission.
**
**THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**http: www.freescale.com
**mail: support@freescale.com
** ###################################################################*/
/*!
** @file RxBuf.h
** @version 01.00
** @brief
**         This component implements a ring buffer for different integer data type.
*/         
/*!
**  @addtogroup RxBuf_module RxBuf module documentation
**  @{
*/         

#ifndef __RxBuf_H
#define __RxBuf_H

/* MODULE RxBuf. */
#include "MCUC1.h" /* SDK and API used */
#include "RxBufconfig.h" /* configuration */

/* Include inherited components */
#include "MCUC1.h"
#include "CS1.h"


#ifdef __cplusplus
extern "C" {
#endif

#if RxBuf_CONFIG_ELEM_SIZE==1
  typedef uint8_t RxBuf_ElementType; /* type of single element */
#elif RxBuf_CONFIG_ELEM_SIZE==2
  typedef uint16_t RxBuf_ElementType; /* type of single element */
#elif RxBuf_CONFIG_ELEM_SIZE==4
  typedef uint32_t RxBuf_ElementType; /* type of single element */
#else
  #error "illegal element type size in properties"
#endif
#if RxBuf_CONFIG_BUF_SIZE<256
  typedef uint8_t RxBuf_BufSizeType; /* up to 255 elements (index 0x00..0xff) */
#else
  typedef uint16_t RxBuf_BufSizeType; /* more than 255 elements, up to 2^16 */
#endif

uint8_t RxBuf_Put(RxBuf_ElementType elem);
/*
** ===================================================================
**     Method      :  RxBuf_Put (component RingBuffer)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t RxBuf_Get(RxBuf_ElementType *elemP);
/*
** ===================================================================
**     Method      :  RxBuf_Get (component RingBuffer)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

RxBuf_BufSizeType RxBuf_NofElements(void);
/*
** ===================================================================
**     Method      :  RxBuf_NofElements (component RingBuffer)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/

void RxBuf_Init(void);
/*
** ===================================================================
**     Method      :  RxBuf_Init (component RingBuffer)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

RxBuf_BufSizeType RxBuf_NofFreeElements(void);
/*
** ===================================================================
**     Method      :  RxBuf_NofFreeElements (component RingBuffer)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/

void RxBuf_Clear(void);
/*
** ===================================================================
**     Method      :  RxBuf_Clear (component RingBuffer)
**     Description :
**         Clear (empty) the ring buffer.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

uint8_t RxBuf_Peek(RxBuf_BufSizeType index, RxBuf_ElementType *elemP);
/*
** ===================================================================
**     Method      :  RxBuf_Peek (component RingBuffer)
**     Description :
**         Returns an element of the buffer without removiing it.
**     Parameters  :
**         NAME            - DESCRIPTION
**         index           - Index of element. 0 peeks the top
**                           element, 1 the next, and so on.
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

#define RxBuf_Deinit() \
   /* nothing to deinitialize */
/*
** ===================================================================
**     Method      :  RxBuf_Deinit (component RingBuffer)
**     Description :
**         Driver de-initialization
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

uint8_t RxBuf_Delete(void);
/*
** ===================================================================
**     Method      :  RxBuf_Delete (component RingBuffer)
**     Description :
**         Removes an element from the buffer
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t RxBuf_Putn(RxBuf_ElementType *elem, RxBuf_BufSizeType nof);
/*
** ===================================================================
**     Method      :  RxBuf_Putn (component RingBuffer)
**     Description :
**         Put a number new element into the buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elem            - Pointer to new elements to be put into
**                           the buffer
**         nof             - number of elements
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t RxBuf_Compare(RxBuf_BufSizeType index, RxBuf_ElementType *elemP, RxBuf_BufSizeType nof);
/*
** ===================================================================
**     Method      :  RxBuf_Compare (component RingBuffer)
**     Description :
**         Compares the elements in the buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**         index           - Index of element. 0 peeks the top
**                           element, 1 the next, and so on.
**       * elemP           - Pointer to elements to compare with
**         nof             - number of elements to compare
**     Returns     :
**         ---             - zero if elements are the same, -1 otherwise
** ===================================================================
*/

uint8_t RxBuf_Getn(RxBuf_ElementType *buf, RxBuf_BufSizeType nof);
/*
** ===================================================================
**     Method      :  RxBuf_Getn (component RingBuffer)
**     Description :
**         Get a number elements into a buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * buf             - Pointer to buffer where to store the
**                           elements
**         nof             - number of elements
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

uint8_t RxBuf_Update(RxBuf_BufSizeType index, RxBuf_ElementType *elemP);
/*
** ===================================================================
**     Method      :  RxBuf_Update (component RingBuffer)
**     Description :
**         Updates the data of an element.
**     Parameters  :
**         NAME            - DESCRIPTION
**         index           - Index of element. 0 peeks the top
**                           element, 1 the next, and so on.
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

/* END RxBuf. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif
/* ifndef __RxBuf_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
